/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package traductor;

import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author spart
 */
public class TraductorFrame extends javax.swing.JFrame {

     
    
    Icon a = new ImageIcon("src/a.png");
    Icon aAcento = new ImageIcon("src/á.png");
    Icon b = new ImageIcon("src/b.png");
    Icon c  = new ImageIcon("src/c.png");
    Icon coma  = new ImageIcon("src/coma.png");
    Icon comillas  = new ImageIcon("src/comillas.png");
    Icon d  = new ImageIcon("src/d.png");
    Icon dosPuntos  = new ImageIcon("src/dos puntos.png");
    Icon e  = new ImageIcon("src/e.png");
    Icon eAcento  = new ImageIcon("src/é.png");
    Icon f  = new ImageIcon("src/f.png");
    Icon g  = new ImageIcon("src/g.png");
    Icon guion  = new ImageIcon("src/guion.png");
    Icon h  = new ImageIcon("src/h.png");
    Icon i  = new ImageIcon("src/i.png");
    Icon iAcento  = new ImageIcon("src/í.png");
    Icon j  = new ImageIcon("src/j.png");
    Icon k  = new ImageIcon("src/k.png");
    Icon l  = new ImageIcon("src/l.png");
    Icon m  = new ImageIcon("src/m.png");
    Icon mayuscula  = new ImageIcon("src/mayuscula.png");
    Icon n  = new ImageIcon("src/n.png");
    Icon numero  = new ImageIcon("src/numero.png");
    Icon enie  = new ImageIcon("src/ñ.png");
    Icon o  = new ImageIcon("src/o.png");
    Icon oAcento  = new ImageIcon("src/ó.png");
    Icon p  = new ImageIcon("src/p.png");
    Icon parentesisIzqui  = new ImageIcon("src/parentesisIzq.png");
    Icon parentesisDere  = new ImageIcon("src/parentesisDere.png");
    Icon puntoYcoma  = new ImageIcon("src/punto y coma.png");
    Icon punto  = new ImageIcon("src/punto.png");
    Icon q  = new ImageIcon("src/q.png");
    Icon r  = new ImageIcon("src/r.png");
    Icon s  = new ImageIcon("src/s.png");
    Icon signosDeadmiracion  = new ImageIcon("src/signos de admiracion.png");
    Icon signoosDePregunta  = new ImageIcon("src/signos de pregunta.png");
    Icon t  = new ImageIcon("src/t.png");
    Icon u  = new ImageIcon("src/u.png");
    Icon uAcento  = new ImageIcon("src/ú.png");
    Icon uDospuntos  = new ImageIcon("src/ü.png");
    Icon v  = new ImageIcon("src/v.png");
    Icon w  = new ImageIcon("src/w.png");
    Icon x  = new ImageIcon("src/x.png");
    Icon y  = new ImageIcon("src/y.png");
    Icon z  = new ImageIcon("src/z.png");
    
    public TraductorFrame() {
        initComponents();
        this.setLocation(450, 90);
        BotonSalir.setToolTipText("Salir");
        BotonTraducir.setToolTipText("Traducir");
        botonBorrar.setToolTipText("Borrar");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        espacioSalida = new javax.swing.JLabel();
        espacioEntrada = new javax.swing.JTextField();
        BotonTraducir = new javax.swing.JButton();
        Label1 = new javax.swing.JLabel();
        botonBorrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Label2 = new javax.swing.JLabel();
        BotonSalir = new javax.swing.JButton();

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Traductor Braille");

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        espacioSalida.setBackground(new java.awt.Color(255, 255, 255));
        espacioSalida.setForeground(new java.awt.Color(255, 255, 255));
        espacioSalida.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        BotonTraducir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/actualizar.png"))); // NOI18N
        BotonTraducir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonTraducirActionPerformed(evt);
            }
        });

        Label1.setBackground(new java.awt.Color(255, 255, 255));
        Label1.setFont(new java.awt.Font("Castellar", 0, 14)); // NOI18N
        Label1.setText("Ingresa la palabra: ");

        botonBorrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/regresar.png"))); // NOI18N
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/logo-tec.png"))); // NOI18N

        Label2.setFont(new java.awt.Font("Castellar", 0, 24)); // NOI18N
        Label2.setText("Traductor Braille");

        BotonSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salir.png"))); // NOI18N
        BotonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Label1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(espacioEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonTraducir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(espacioSalida, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(104, 104, 104)
                            .addComponent(Label2)
                            .addGap(121, 121, 121))))
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(Label2))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonTraducir))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(espacioEntrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Label1))
                        .addGap(21, 21, 21)))
                .addComponent(espacioSalida, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(BotonSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonTraducirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonTraducirActionPerformed
        
        String palabra = espacioEntrada.getText();
        char [] arregloPalabra = new char[palabra.length()];
        
        for (int i = 0; i < arregloPalabra.length; i++) {
           
            arregloPalabra[i] = palabra.charAt(i);
          
        }
        for(char recorrido: arregloPalabra){  // recorremos el arreglo
            String letra = String.valueOf(recorrido);
             
             
            switch(letra){
            
            case "a":               
                espacioSalida.setIcon(a);
                break;
            case "á": 
                espacioSalida.setIcon(aAcento);
                break;
            case "b": 
                espacioSalida.setIcon(b);
                break;
            case "c": 
                espacioSalida.setIcon(c);
                break;
            case ",": 
                espacioSalida.setIcon(coma);
                break;
            case " ' ": 
                espacioSalida.setIcon(comillas);
                break;
            case "d": 
                espacioSalida.setIcon(d);
                break;
            case ":": 
                espacioSalida.setIcon(dosPuntos);
                break;
            case "e": 
                espacioSalida.setIcon(e);
                break;
            case "é": 
                espacioSalida.setIcon(eAcento);
                break;
            case "f": 
                espacioSalida.setIcon(f);
                break;
            case "g": 
                espacioSalida.setIcon(g);
                break;
            case "-": 
                espacioSalida.setIcon(guion);
                break;
            case "h": 
                espacioSalida.setIcon(h);
                break;
            case "i": 
                espacioSalida.setIcon(i);
                break;
            case "í": 
                espacioSalida.setIcon(iAcento);
                break;
            case "j": 
                espacioSalida.setIcon(j);
                break;
            case "k": 
                espacioSalida.setIcon(k);
                break;
            case "l": 
                espacioSalida.setIcon(l);
                break;
            case "m": 
                espacioSalida.setIcon(m);
                break;
            case "n": 
                espacioSalida.setIcon(n);
                break;
            case "ñ": 
                espacioSalida.setIcon(enie);
                break;
            case "o": 
                espacioSalida.setIcon(o);
                break;
            case "ó": 
                espacioSalida.setIcon(oAcento);
                break;
            case "p": 
                espacioSalida.setIcon(p);
                break;
            case "(": 
                espacioSalida.setIcon(parentesisIzqui);
                break;
            case ")": 
                espacioSalida.setIcon(parentesisDere);
                break;
            case ";": 
                espacioSalida.setIcon(puntoYcoma);
                break;
            case ".": 
                espacioSalida.setIcon(punto);
                break;
            case "q": 
                espacioSalida.setIcon(q);
                break;
            case "r": 
                espacioSalida.setIcon(r);
                break;
            case "s": 
                espacioSalida.setIcon(s);
                break;
            case "¡": 
                espacioSalida.setIcon(i);
                break;
            case "!": 
                espacioSalida.setIcon(signosDeadmiracion);
                break;
            case "?": 
                espacioSalida.setIcon(signoosDePregunta);
                break;
            case "t": 
                espacioSalida.setIcon(t);
                break;
            case "u": 
                espacioSalida.setIcon(u);
                break;
            case "ú": 
                espacioSalida.setIcon(uAcento);
                break;
            case "ü": 
                espacioSalida.setIcon(uDospuntos);
                break;
            case "v": 
                espacioSalida.setIcon(v);
                break;
            case "w": 
                espacioSalida.setIcon(w);
                break;
            case "x": 
                espacioSalida.setIcon(x);
                break;
            case "y": 
                espacioSalida.setIcon(y);
                break;
            case "z": 
                espacioSalida.setIcon(z);
                break;
        }
         
        }
        
        
       
        
    }//GEN-LAST:event_BotonTraducirActionPerformed

    private void BotonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonSalirActionPerformed
        System.exit(0);
        
    }//GEN-LAST:event_BotonSalirActionPerformed

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonBorrarActionPerformed
        espacioEntrada.setText(null);
        
    }//GEN-LAST:event_botonBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TraductorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TraductorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TraductorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TraductorFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TraductorFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonSalir;
    private javax.swing.JButton BotonTraducir;
    private javax.swing.JLabel Label1;
    private javax.swing.JLabel Label2;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JTextField espacioEntrada;
    private javax.swing.JLabel espacioSalida;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
